# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: yarn build:test
      - run: yarn coverage
      - run: ls .report_e2e
      - run: ls .report_unit
      - uses: codecov/codecov-action@v3
        with:
          flags: unit
          file: .report_unit/lcov.info
      - uses: codecov/codecov-action@v3
        with:
          flags: e2e
          file: .report_e2e/lcov.info
